[[headers]]
  for = "/assets/css/style.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/assets/fonts/fontawesome/css/all.min.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/images/main.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[redirects]]
  from = "/"
  to = "/en"
  status = 301
  force = true
  query = {path = ":path"}
  conditions = {Language = ["en"]}
[[redirects]]
  from = "/"
  to = "/hu"
  status = 301
  force = true
  query = {path = ":path"}
  conditions = {Language = ["hu"]}